version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build_and_deploy:
    docker:
      - image: cimg/node:$NODE_VERSION
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Build the project
          command: npm run build
#      - ssh:
#          name: Deploy to production
#          host: $SSH_HOST
#          user: $SSH_USER
#          private_key: ~/circleci/ssh-key.pem
#          commands:
#            - 'mkdir -p /var/www/todo-app'
#            - 'rsync -avz --delete dist/ $SSH_USER@$SSH_HOST:/var/www/todo-app'
#            - 'echo "Deployed successfully"'
#      - run:
#          name: Restart NGINX using Docker Compose
#          command: |
#            docker-compose -f /git/todo-frontend/docker/todo-app/docker-compose.yml up -d

workflows:
  Node:
    jobs:
      - build_and_deploy:
          context:
            - build-context
