# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@2.2.0

# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/node:16.20.1

    #working_directory: /var/www

    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
       - checkout

      # Install Docker
    #- setup_remote_docker

      #      - restore_cache:
      #          keys:
      #            - v1-deps-{{ checksum package.json }}
      #
      #      # Install dependencies
      #      - run:
      #          name: Node build
      #          command: npm install
      #
      #      - save_cache:
      #          paths:
      #            - node_modules
      #          key: v1-deps-{{ checksum package.json }}

      # Save shared data
      #      - persist_to_workspace:
      #          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
      #          # taken to be the root directory of the workspace.
      #          root: .
      #          # Must be relative path from root
      #          paths:
      #            - target/todo-backend-*.jar
      #            - docker

      # Then run your tests!
      #- run:
      #    name: Test
      #    command: mvn test

  docker-push:
    docker:
      - image: cimg/node:16.20.1
    steps:
      # Checkout the code as the first step.
      - checkout

      # Install Docker
      - setup_remote_docker

      # Login into Docker Hub
      - run:
          name: Docker login
          command: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin

      # Build Docker image
      - docker/build:
          docker-context: .
          path: ./docker
          dockerfile: todo-frontend.dockerfile
          image: ddrram/todo-frontend
          tag: 1.3.$CIRCLE_BUILD_NUM

      # Push Docker image
      - docker/push:
          image: ddrram/todo-frontend
          tag: 1.3.$CIRCLE_BUILD_NUM

  deploy:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2b:a4:ba:38:78:e6:13:5e:53:bc:8e:8b:59:3a:c0:fe"
      - run:
          name: Create SSH folder
          command: mkdir -p ~/.ssh
      - run:
          name: Add known host
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy over SSH
          command: ssh $SSH_USER@$SSH_HOST 'cd ~/logs && touch ssh-todo-frontend-$(date +"%Y-%m-%d_%H-%M-%S").log'
  output:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run: echo hi :)

workflows:
  node-build:
    jobs:
      - output
      #- deploy:
      #    context:
      #      - build-context
      #    requires:
      #      - docker-push
