version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  deploy:
    machine: # executor type
      image: ubuntu-2004:2022.07.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c1:b0:02:b6:9d:26:29:a6:8c:74:0e:eb:12:1a:f6:f4"
      #- run:
      #    name: Create SSH folder
      #    command: mkdir -p ~/.ssh
      #- run:
      #    name: Add known host
      #    command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST -f "touch todo-frontend-$(date +"%Y-%m-%d_%H-%M-%S").log && exit"

workflows:
  react-frontend:
    jobs:
      - deploy:
          context:
            - build-context
#          requires:
#            - docker-push
