version: 2.1

#orbs:
#  docker: circleci/docker@2.2.0

jobs:
  deploy:
    machine: # executor type
      image: ubuntu-2004:2022.07.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2b:a4:ba:38:78:e6:13:5e:53:bc:8e:8b:59:3a:c0:fe"
      #- run:
      #    name: Create SSH folder
      #    command: mkdir -p ~/.ssh
      #- run:
      #    name: Add known host
      #    command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy over SSH
          command: |
            ssh root@212.227.201.99 touch todo-frontend-$(date +"%Y-%m-%d_%H-%M-%S").log && exit

workflows:
  nodejs:
    jobs:
      - deploy:
          context:
            - build-context
#          requires:
#            - docker-push
