version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  deploy:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2b:a4:ba:38:78:e6:13:5e:53:bc:8e:8b:59:3a:c0:fe"
      - run:
          name: Create SSH folder
          command: mkdir -p ~/.ssh
      - run:
          name: Add known host
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy over SSH
          command: ssh $SSH_USER@$SSH_HOST 'cd ~/logs && touch ssh-todo-frontend-$(date +"%Y-%m-%d_%H-%M-%S").log'

workflows:
  node-build:
    jobs:
      - deploy:
          context:
            - build-context
#          requires:
#            - docker-push
