version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  test:
    docker:
      - image: cimg/node:18.7.0
    steps:
      - run: echo "This is pipeline number << pipeline.number >>"
  build-push:
    docker:
      - image: cimg/node:$NODE_VERSION
    steps:
      # Checkout the code as the first step.
      - checkout

      # Install Docker
      - setup_remote_docker

      # Login into Docker Hub
      - run:
          name: Docker login
          command: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin

      # Build Docker image
      - docker/build:
          docker-context: .
          path: ./docker
          dockerfile: todo-frontend.dockerfile
          image: ddrram/todo-frontend
          tag: 1.3.$CIRCLE_BUILD_NUM

      # Push Docker image
      - docker/push:
          image: ddrram/todo-frontend
          tag: 1.3.$CIRCLE_BUILD_NUM
  deploy:
    docker:
      - image: cimg/node:$NODE_VERSION
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2b:a4:ba:38:78:e6:13:5e:53:bc:8e:8b:59:3a:c0:fe"
      - run:
          name: Add known host
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "echo 1.3.$CIRCLE_BUILD_NUM > ~/logs/todo-frontend.log && exit"

workflows:
  build-push-deploy:
    jobs:
      - test
#      - build-push:
#          context:
#            - build-context
#      - deploy:
#          context:
#            - build-context
#          requires:
#            - build-push
