version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build-push:
    docker:
      - image: cimg/node:$NODE_VERSION
    environment:
      BUILD_NUMBER: << pipeline.number >>
    steps:
      # Checkout the code as the first step.
      - checkout

      # Install Docker
      - setup_remote_docker

      # Echo build number
      - run:
          name: Echo build number
          command: echo $BUILD_NUMBER

      # Login into Docker Hub
      - run:
          name: Docker login
          command: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin

      # Build Docker image
      - docker/build:
          docker-context: .
          path: ./docker
          dockerfile: todo-frontend.dockerfile
          image: ddrram/todo-frontend
          tag: 1.3.$BUILD_NUMBER

      # Push Docker image
      - docker/push:
          image: ddrram/todo-frontend
          tag: 1.3.$BUILD_NUMBER
  deploy:
    docker:
      - image: cimg/node:$NODE_VERSION
    environment:
      BUILD_NUMBER: << pipeline.number >>
    steps:
      - run:
          name: Timestamp
          command: echo timestamp=$(date +"%Y-%m-%d_%H-%M-%S")
      - add_ssh_keys:
          fingerprints:
            - "2b:a4:ba:38:78:e6:13:5e:53:bc:8e:8b:59:3a:c0:fe"
      - run:
          name: Add known host
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "echo 1.3.$BUILD_NUMBER > ~/logs/todo-frontend.log && cd ~/git/todo-backend && ./deploy.sh && exit"

workflows:
  Node:
    jobs:
      - build-push:
          context:
            - build-context
      - deploy:
          context:
            - build-context
          requires:
            - build-push
