version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build_and_deploy:
    docker:
      - image: cimg/node:$NODE_VERSION
    steps:
      - checkout
      - run:
          name: npm i
          command: |
            npm i
      - run:
          name: npm run build
          command: npm run build
      - run:
          name: Compress .tar.gz
          command: |
            tar -czvf todo-app.tar.gz todo-app
      - add_ssh_keys:
          fingerprints:
            - "2b:a4:ba:38:78:e6:13:5e:53:bc:8e:8b:59:3a:c0:fe"
      - run:
          name: Add known host
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Upload via scp
          command: |
            scp todo-app.tar.gz $SSH_USER@$SSH_HOST:/var/www
      - run:
          name: Extract and deploy via ssh
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /var/www && tar -xzvf todo-app.tar.gz"

workflows:
  deploy:
    jobs:
      - build_and_deploy:
          context:
            - build-context
