version: "3"

services:
  todo-nginx:
    container_name: todo-nginx
    image: todo-nginx-dev
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - todo-backend
      - todo-frontend
      - todo-keycloak
    networks:
      - todo-app

  todo-frontend:
    container_name: todo-frontend
    image: todo-frontend
    ports:
      - "3000:3000"
    networks:
      - todo-app

  todo-backend:
    container_name: todo-backend
    image: todo-backend
    ports:
      - "5000:5000"
    volumes:
      - ./logs/:/opt/app/logs
    depends_on:
      - todo-db
    networks:
      - todo-app
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://todo-db:3306/todo-db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "todo",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.datasource.initialization-mode": "always",
        "spring.jpa.show-sql": "true",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"}'

  todo-db:
    container_name: todo-db
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: todo-db
      MYSQL_ROOT_PASSWORD: todo
    ports:
      - "3306:3306"
    volumes:
      - "C:/Users/ddr_r/databases/todo-db:/var/lib/mysql:rw"
    networks:
      - todo-app

  todo-postgres:
    container_name: todo-postgres
    image: postgres
    volumes:
      - "C:/Users/ddr_r/databases/todo-postgres:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: root
      POSTGRES_PASSWORD: todo
    networks:
      - todo-app

  todo-keycloak:
    container_name: todo-keycloak
    image: todo-keycloak
    #    image: quay.io/keycloak/keycloak:latest
    command:
      - start
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: 'true'
    #      KC_HOSTNAME_URL: https://localhost:8443
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - todo-postgres
    networks:
      - todo-app

networks:
  todo-app: { }

volumes:
  todo-db: { }
  todo-postgres: { }

# docker-compose -f docker/docker-compose-dev.yaml up -d
