version: "3"

services:
  todo-nginx:
    container_name: todo-nginx
    image: ddrram/todo-nginx-prod:1.3.1
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - todo-backend
      - todo-frontend
      - todo-keycloak
    networks:
      - todo-app
    volumes:
      - /root/usr/share/certbot/conf:/etc/letsencrypt
      - /root/usr/share/certbot/www:/var/www/certbot
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  todo-certbot-renewal:
    image: certbot/certbot
    container_name: todo-certbot-renewal
    depends_on:
      - todo-nginx
    volumes:
      - /root/usr/share/certbot/conf:/etc/letsencrypt
      - /root/usr/share/certbot/www:/var/www/certbot
    networks:
      - todo-app
    entrypoint: sh -c "certbot renew && sleep 7d"
  #    command: renew
  #    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  todo-frontend:
    container_name: todo-frontend
    image: ddrram/todo-frontend:${TODO_FRONTEND_VERSION}
    ports:
      - "3000:3000"
    networks:
      - todo-app
    restart: unless-stopped

  todo-backend:
    container_name: todo-backend
    image: ddrram/todo-backend:${TODO_BACKEND_VERSION}
    ports:
      - "5000:5000"
    volumes:
      - /root/logs:/opt/app/logs
    depends_on:
      - todo-db
    networks:
      - todo-app
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://todo-db:3306/todo-db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "todo",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.datasource.initialization-mode": "always",
        "spring.jpa.show-sql": "true",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"}'
    restart: unless-stopped

  todo-db:
    container_name: todo-db
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: todo-db
      MYSQL_ROOT_PASSWORD: todo
    ports:
      - "3306:3306"
    volumes:
      - "/root/usr/share/databases/todo-db:/var/lib/mysql:rw"
    networks:
      - todo-app
    restart: unless-stopped

  todo-postgres:
    container_name: todo-postgres
    image: postgres
    volumes:
      - "/root/usr/share/databases/todo-postgres:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: root
      POSTGRES_PASSWORD: todo
    networks:
      - todo-app

  todo-keycloak:
    container_name: todo-keycloak
    image: ddrram/todo-keycloak-prod:1.0.0
    #    image: quay.io/keycloak/keycloak:latest
    command:
      - start
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: 'true'
      KC_HOSTNAME: todo-app.tech
    #      KC_HOSTNAME_ADMIN: todo-app.tech
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - todo-postgres
    networks:
      - todo-app

networks:
  todo-app: { }

volumes:
  todo-db: { }
  todo-postgres: { }

# docker-compose -f docker/docker-compose-prod.yaml up -d
