events {}

http {

    include /etc/nginx/mime.types;

    server {
    	listen 80;

    	server_name todotask.app;

    	location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

    	location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;

        root /var/www/apps/todo-app;

        index index.html;

        server_name todotask.app;

        ssl_certificate /etc/letsencrypt/live/todotask.app/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/todotask.app/privkey.pem;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }

#         location /auth {
#             proxy_pass https://todo-keycloak:8443;
#             proxy_redirect off;
#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#             proxy_set_header X-Forwarded-Proto $scheme;
#             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         }

        # location = /favicon.ico {
        #     access_log off;
        #     log_not_found off;
        #     try_files $uri =204;
        # }

        # # deny access to dotfiles (like /.env)
        # location ~ /\.
        # {
        #     deny all;
        #     access_log off;
        #     log_not_found off;
        # }

        # location ~* \.(?:css|js|png|jpg|jpeg|gif|ico|json)$ {
        #     try_files $uri =404;
        #     access_log off;
        #     expires 7d;
        # }

        # location = /index.html {
        #     # serve index directly to avoid re-running try_files in the prefix location
        #     root /var/www/apps/todo-app;
        #     access_log off;
        # }

        # location / {
        #     try_files $uri $uri/ /index.html =200;
        # }

        location /api {
            proxy_pass http://todo-backend:5000;
        }

        location ~* ^.+\.css$ {
            default_type text/css;
        }
    }
}

